databases:
  - name: portfoliosql
    plan: free
    databaseName: portfolio_db
    user: portfolio_user

services:
  - type: web
    name: amrita-portfolio
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfoliosql
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
